//Lista de usuarios
GET http://localhost:3000/api/usuarios

###

//Obtener un usuario

GET http://localhost:3000/api/usuarios/user





###

//CREAR USUARIO

POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "Carmelo",
    "email": "Carmelo@gmail.com",
    "password": "Carmelo123"
}

###

//LOGAR USUARIO
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json


{
    "valorLogin": "Carmelo",
    "password": "Carmelo123"
}