//OBTENER TODOS LOS JUEGOS

GET http://localhost:3000/api/juegos

###

//OBTENER UN JUEGO POR ID juegos/ID

GET http://localhost:3000/api/juegos/


###

//OBTENER TODOS LOS MODOS DE JUEGO POR CADA JUEGO (ID)

GET http://localhost:3000/api/juegos/2/modos

###

//OBTENER TODAS LAS PARTIDAS POR CADA JUEGO (ID)

GET http://localhost:3000/api/juegos/0/partidas

###

//OBTENER TODOS LOS RANGOS POR CADA JUEGO(ID)

GET http://localhost:3000/api/juegos/0/rangos

###

//OBTENER NUMERO MÁXIMO DE JUGADORES POR MODO DE JUEGO(ID)

GET http://localhost:3000/api/juegos/modos/1/jugadores