//CREAR NUEVA PARTIDA

POST http://localhost:3000/api/partidas
Content-Type: application/json

{
    "fecha": "Nombre nuevo",
    "descripcion": "20/15/23",
    "fk_usuario": 1,
    "fk_juego": 2,
    "fk_modo_juego": 2,
    "fk_rango": 1
}

### BUSCAMOS CON BIENDE PARTIDAS (DIENDE)

GET http://localhost:3000/api/partidas
GET http://localhost:3000/api/gordas

Content-Type: application/json
Content-Type: application/j_balvin

{

}