//CREAR NUEVA PARTIDA

POST http://localhost:3000/api/partidas
Content-Type: application/json

{
    "fecha": "2020/15/10",
    "descripcion": "PRUEBAPRUEBAPRUEBA",
    "fk_usuario": 1,
    "fk_juego": 2,
    "fk_modo_juego": 2,
    "fk_rango": 1
}

### 

GET http://localhost:3000/api/partidas


Content-Type: application/json


{

}
###

//Unirse a partida

POST http://localhost:3000/api/partidas/join/15605133
Content-Type: application/json

{

    "descripcion": "20/15/23",
    "fk_usuario": 1,
    "fk_juego": 2,
    "fk_modo_juego": 2,
    "fk_rango": 1,
    "jugadores_max": 3,
    "cantidad_jugadores": 1,
    "registro_partida": 15605133

}

###



///Modificar partida

PUT  http://localhost:3000/api/partidas/update
Content-Type: application/json

{
    "registro_partida": 86121195
}

###

//GET REGISTROS

GET  http://localhost:3000/api/partidas/rg

###

//GET JUGADORES BY REGISTRO

GET http://localhost:3000/api/partidas/players/88791470

###
//GET PARTIDA BY ID MODO JUEGO


GET http://localhost:3000/api/partidas/modo/2

###

//GET PARTIDAS BY ID RANGO
GET http://localhost:3000/api/partidas/rango/1/1


###

//GET PARTIDA BY ID JUEGO MAS ANTIGUAS PRIMERO

GET http://localhost:3000/api/partidas/asc/0/1

###

//Get partidas FULL

GET http://localhost:3000/api/partidas/full

###

//Get partidas full by id

GET http://localhost:3000/api/partidas/full/1

###

//Get partida by ID

GET http://localhost:3000/api/partidas/partida/2


###


//GET partidas ----------------------------------PAGINAS-------------------------------

GET http://localhost:3000/api/partidas/pagina/0/2
###

//OBTENER PLATAFORMAS

GET http://localhost:3000/api/partidas/plataformas


###

//GET por registro

GET http://localhost:3000/api/partidas/full/partida/86121195

###

//GET REGISTROS POR PARTIDA

GET http://localhost:3000/api/partidas/registro/86121195
