//CREAR NUEVA PARTIDA

POST http://localhost:3000/api/partidas
Content-Type: application/json

{
    "fecha": "Nombre nuevo",
    "descripcion": "20/15/23",
    "fk_usuario": 1,
    "fk_juego": 2,
    "fk_modo_juego": 2,
    "fk_rango": 1
}

###

//Get partidas FULL

GET http://localhost:3000/api/partidas/full

###

//Get partidas full by id

GET http://localhost:3000/api/partidas/full/1

###

//Get partida by ID

GET http://localhost:3000/api/partidas/partida/2

###

//OBTENER PLATAFORMAS

GET http://localhost:3000/api/partidas/plataformas