//OBTENER TODOS LOS USUARIOS
GET http://localhost:3000/api/usuarios

###

//OBTENER USUARIO POR ID

GET http://localhost:3000/api/usuarios/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjIyLCJjYWR1Y2lkYWQiOjE2MDg0NjExOTUsImlhdCI6MTYwNzU5NzE5NX0.HRnCeSPoAW995VRmORFm10eAaOrQCeSDB8K34R2_jqI


###

//CREAR USUARIO

POST http://localhost:3000/api/login/registro
Content-Type: application/json

{
    "username": "Carmelo",
    "email": "Carmelo@gmail.com",
    "password": "Carmelo123"
}

###

//LOGAR USUARIO
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "valorLogin": "Paria",
    "password": "Paria12"
}

###

//USUARIO LOGADO

GET  http://localhost:3000/api/usuarios/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjIyLCJjYWR1Y2lkYWQiOjE2MDg0NjExOTUsImlhdCI6MTYwNzU5NzE5NX0.HRnCeSPoAW995VRmORFm10eAaOrQCeSDB8K34R2_jqI